version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8000"
  
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-db:/demoapp

volumes:
 mysql-db: